### PR TITLE
:boom: Fix #86 and #87

### LINKED ISSUE #86: PersistEngine Unlock is broken

### PR DESCRIPTION
**Pull request by ilaborie**
Solve unlock issue by introduction executionId

### CODE REVIEW

File: core/src/test/kotlin/io/saagie/updatarium/log/InMemoryAppenderTest.kt [hunk 1]
```diff
@@ -106,7 +104,7 @@ internal class InMemoryAppenderTest {
             level = Level.INFO,
             onSuccessStoreLogs = true,
             onErrorStoreLogs = true
-        ) { event -> event.message!! }
+        ) { event -> event.message?:throw IllegalStateException() }
```
Comment (rcapraro) [inline core/src/test/kotlin/io/saagie/updatarium/log/InMemoryAppenderTest.kt]: missing spaces, should be `event.message ? :throw IllegalStateException()`

File: core/src/test/kotlin/io/saagie/updatarium/model/ChangeLogTest.kt [hunk 2]
```diff
@@ -107,40 +103,32 @@ class ChangeLogTest {
...
+            }
+        }
 
         val config = UpdatariumConfiguration(failFast = true, persistEngine = TestPersistEngine())
         val changelogReport = changelog.execute(config)
         assertThat(changelogReport.changeSetExceptions).hasSize(1)
         with(changelogReport.changeSetExceptions.first()) {
             assertThat(this.changeSet).isEqualTo(changelog.changeSets.first())
-            assertThat(this.e!!).hasMessage("Fail in action")
+            assertThat(this.e?:throw IllegalStateException()).hasMessage("Fail in action")
```
Comment (rcapraro) [inline core/src/test/kotlin/io/saagie/updatarium/model/ChangeLogTest.kt]: missing space around the Elvis operator
